alloy:
  clustering:
    enabled: true
  configMap:
    content: ''
    create: false
    key: null
    name: meraki-config
  enableReporting: true
  envFrom: []
  extraArgs: []
  extraEnv: []
  extraPorts: []
  listenAddr: 0.0.0.0
  listenPort: 12345
  listenScheme: HTTP
  mounts:
    dockercontainers: false
    extra: []
    varlog: false
  resources: {}
  securityContext: {}
  stabilityLevel: public-preview
  storagePath: /tmp/alloy
  uiPathPrefix: /
configReloader:
  customArgs: []
  enabled: true
  image:
    digest: ''
    registry: ghcr.io
    repository: jimmidyson/configmap-reload
    tag: v0.12.0
  resources:
    requests:
      cpu: 1m
      memory: 5Mi
  securityContext: {}
controller:
  affinity: {}
  autoscaling:
    enabled: false
    maxReplicas: 5
    minReplicas: 1
    scaleDown:
      policies: []
      selectPolicy: Max
      stabilizationWindowSeconds: 300
    scaleUp:
      policies: []
      selectPolicy: Max
      stabilizationWindowSeconds: 0
    targetCPUUtilizationPercentage: 0
    targetMemoryUtilizationPercentage: 80
  dnsPolicy: ClusterFirst
  enableStatefulSetAutoDeletePVC: false
  extraAnnotations: {}
  extraContainers: []
  hostNetwork: false
  hostPID: false
  initContainers: []
  nodeSelector: {}
  parallelRollout: true
  podAnnotations: {}
  podLabels: {}
  priorityClassName: ''
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
  type: daemonset
  updateStrategy: {}
  volumeClaimTemplates: []
  volumes:
    extra: []
crds:
  create: true
fullnameOverride: null
global:
  image:
    pullSecrets: []
    registry: ''
  podSecurityContext: {}
image:
  digest: null
  pullPolicy: IfNotPresent
  pullSecrets: []
  registry: docker.io
  repository: grafana/alloy
  tag: null
ingress:
  annotations: {}
  enabled: true
  extraPaths: []
  faroPort: 12345
  hosts:
    - meraki-agent.k3-prod.thetmg.com
  labels: {}
  path: /
  pathType: Prefix
  tls: []
  ingressClassName: nginx
nameOverride: null
rbac:
  create: true
service:
  annotations: {}
  clusterIP: ''
  enabled: true
  internalTrafficPolicy: Cluster
  nodePort: 31128
  type: ClusterIP
serviceAccount:
  additionalLabels: {}
  annotations: {}
  create: true
  name: null
serviceMonitor:
  additionalLabels: {}
  enabled: false
  interval: ''
  metricRelabelings: []
  relabelings: []
  tlsConfig: {}
